Repository TammyAlok2/React-Advance-Projects, pull requests merged in 2023-10, with the labels that each got.

#2 contribution file successfully updated
  Contribution.md
  New file added in the react projects
  README.md
  hjjhhj
  new file
Labels: hactoberfest-accepted, hactoberfest

#4 added code of conduct file
  CODE_OF_CONDUCT.md
Labels: hactoberfest-accepted, hactoberfest

#6 playlist addition
  Youtube-clone/myapp/src/Components/Playlist.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#11 added html code
  English-Speaking website/public/index1.html
  English-Speaking website/src/Components/todo.css
Labels: hacktoberfest-accepted, hacktoberfest

#13 Added js file
  English-Speaking website/src/Components/todo.css
  English-Speaking website/src/Components/todo.html
  English-Speaking website/src/Components/todo.js
Labels: hacktoberfest-accepted, hacktoberfest

#14 music app created
  Youtube-clone/myapp/src/Components/Music.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#15 Added Trailers Section to integrate trailers in the project.
  Youtube-clone/myapp/src/Components/Trailers.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#17 sound file updated
  Youtube-clone/myapp/src/Components/sound.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#18 this is a song.jsx file
  Youtube-clone/myapp/src/Components/song.jsx
  song.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#19 video is added
  Youtube-clone/myapp/src/Components/Music.jsx
  Youtube-clone/myapp/src/Components/Playlist.jsx
  Youtube-clone/myapp/src/Components/Video.jsx
  Youtube-clone/myapp/src/Components/YoutubeVideo.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#10 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#20 React Project
  English-Speaking website/src/data.jsx
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest new
